services:

  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Shanghai
      - PGTZ=Asia/Shanghai
      # - POSTGRES_INITDB_ARGS=--icu-locale=zh-CN
    command: >
      postgres
      -c listen_addresses='*'
      -c timezone='Asia/Shanghai'
      -c log_timezone='Asia/Shanghai'
      -c datestyle='iso, dmy'
      -c lc_messages='C'
      -c lc_monetary='C'
      -c lc_numeric='C'
      -c lc_time='C'
    networks:
      - postgres-network
    ports:
      - "65432:5432"
volumes:
  app-db-data:
networks:
  postgres-network:
    external: false