name: apis_dataservice
upstream:
  nodes:
    - host: 192.168.33.35
      port: 7734
      weight: 1
  timeout:
    connect: 600
    send: 600
    read: 600
  type: roundrobin
  scheme: http
  pass_host: pass
  keepalive_pool:
    idle_timeout: 60
    requests: 1000
    size: 320